# -*- coding: utf-8 -*-
"""Khub_Colab5_5th-Feb-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdphxxJorqDhH5qgUO1r62mJQKNpI1Kg

Name :- KALEPU MOHAH VEERA MANIKANTA

ROLL NO :- 23B21A4316

---


Q. write a function that returns sum, subtracton, multiplucation and division of two numbers.
"""

def arithmetic_opertations(a,b):
  sum_result=a+b
  sub_result=a-b
  mul_result=a*b
  div_result=a/b if b!=0 else "No Solution divsion by zero"
  return sum_result,sub_result,mul_result,div_result

Pen = 10
Book = 5
results = arithmetic_operations(Pen, Book)
print(f"Sum: {results[0]}, Subtraction: {results[1]}, Multiplication: {results[2]}, Division: {results[3]}")