# -*- coding: utf-8 -*-
"""Khub_Colab3_3rd-Feb-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eSurHko9wQtEiP9IRMKXEcg1x0YbnBH
"""

Mohan = int(input("Enter an integer: "))
for i in range(1, Mohan + 1):
    # Skip even numbers using continue
    if i % 2 == 0:
        continue

    if i == 10:
        print("Encountered 7, performing an action!")

    print(i)