# -*- coding: utf-8 -*-
"""Khub_Colab2_1-Feb-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FK_FDuV7CNECaG05Lj5jhdvuofeQ-V_M

Name : Kalepu Mohan Veera Manikanta

Roll No : 23B21A4316


---
Q. Write a python program to take a number input and print even or odd
"""

num=int(input("Enter a number:"))
if(num%2==0):
  print("The number is even")
else:
  print("The number is odd")

"""Check Divisibility by 2:

If a number is divisible by 2 (i.e., number % 2 == 0), it is an even number.
Otherwise, it is an odd number.
"""