# -*- coding: utf-8 -*-
"""Khub_Colab4_4th-Feb-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbK4nvFsHS6G6m9oCvxbfhRdXidXiZfz

Name :- KALEPU MOHAH VEERA MANIKANTA

ROLL NO :- 23B21A4316

---


Q. write your understanding on how functions work in python and return statement.
"""

def add(a,b):
  return a+b

result=add(5,3)
print(result)