# -*- coding: utf-8 -*-
"""Khub_Colab1_31-jan-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWd2MflajK-uVRNmNpF6am2DjKl_apaS

Name : Kalepu Mohan Veera Manikanta

Roll No : 23B21A4316

Q.Write a python program to take two inputs and print the values of addition, subtraction, multiplication and division of two numbers
"""

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

# Performing arithmetic operations
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b if b != 0 else "Undefined (division by zero)"

# Displaying results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

"""**Logic:**

1. Take Input: The program prompts the user to enter two integers using the input() function. Since input() returns a string, the int() function converts it into an integer.

2. Perform Addition: The two integers are added together and stored in variable

3. Display Output: The sum is printed using the print() function.
"""